### ISSUE TITLE
Reference to panel's DOM

### ISSUE THREAD

**Issue by cadorn** [firebug/devtools-extension-examples#1]
In my panel's `initialize()` method, how do I get access to the DOM of my loaded `panel.html`?

See: https://github.com/firephp/firephp-for-firebug.next/blob/8ccf127d81dd3d76dfea786df410bc4e7d4e01c6/client/lib/panel.js#L29

**Comment by cadorn** [comment]
$feature https://github.com/firephp/firephp-for-firebug.next/issues/1

**Comment by cadorn** [comment]
I suppose I cannot reference the DOM due to inter-process boundary, but how do I post and receive messages between the panel DOM and the panel JS?

**Comment by cadorn** [comment]
`self.port` does not work

**Comment by janodvarko** [comment]
If the panel's iframe uses type="content", which is the recommended way, you need to use message manager to send messages between the chrome scope and the iframe.

A good example of how to send these message is in the Add-on SDK.
post-repl:
- sending message to the content
  https://github.com/mozilla/addon-sdk/blob/master/examples/actor-repl/index.js#L26
- receive message within the content
  https://github.com/mozilla/addon-sdk/blob/master/examples/actor-repl/data/index.html#L116
- Here is implementation of the postMessage
  https://github.com/mozilla/addon-sdk/blob/master/lib/dev/panel.js#L129

Honza

**Comment by cadorn** [comment]
This does not seem to work. I am not trying to start a debug session. When I use this and call `this.debuggee.start()` I get a remote actor protocol message in the panel. I am simply trying to message with the content in the panel. Any change someone can add an example. I'll add skeleton if you give me access to this repo.

**Comment by cadorn** [comment]
JS: https://github.com/firephp/firephp-for-firebug.next/blob/f47b4c3d2358d905c7b5d0a670fbc02e72b64d56/components/ui/devtools-panel.js#L25-L36

HTML: https://github.com/firephp/firephp-for-firebug.next/blob/f47b4c3d2358d905c7b5d0a670fbc02e72b64d56/client/data/panel.html#L8-L21

**Comment by janodvarko** [comment]
Here is an example:
https://github.com/firebug/devtools-extension-examples/tree/master/MessageManager

Honza

**Comment by janodvarko** [comment]
You should have an access to this repo now.

Honza

**Comment by cadorn** [comment]
Thanks! This is way more than I could have figured out. These little examples are key to the success of extensions. As soon as each example has an automated test we should run these against SDK changes.

**Comment by janodvarko** [comment]
Yes, the tests are needed.

Honza
