### ISSUE TITLE
Add example to access "window" global in the web page

### ISSUE THREAD

**Issue by nt1m** [firebug/devtools-extension-examples#4]
This pretty covers most of devtools use cases.
- If you're accessing audio nodes, or animation players on a page you'll likely need access the window property or use a bridge
- If you want to create a Blob URL in the web page from devtools that come from the content, you'll likely need to do that as well. (Create a blob from the devtools --> Pass it to the content --> create an URL there). Note that you can't create a blob URL directly from the devtools, since it does not work with e10s

**Comment by janodvarko** [comment]
So, what about an example that allows to get/set window title?

Honza

**Comment by janodvarko** [comment]
Let me know how it works for you

Honza

**Comment by nt1m** [comment]
I'll get back to you once I try it, thanks for the example !

**Comment by nt1m** [comment]
So I've just tried it out, and I'm a bit deceived that this doesn't work on other runtimes than Firefox. The reason I wanted to use an actor is because I needed to support those targets as well.

Anyway, I tried to eliminate the use of listTabs like this : https://pastebin.mozilla.org/8841569 with no success. And now it's failing on every target : 

<pre>
Error: Can't manage front without an actor ID.
Ensure server supports actorRegistry.: Front<.manage@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/protocol.js:1133:1
ActorRegistryFront<.initialize@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/actor-registry.js:115:5
constructor@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/core/heritage.js:146:23
ToolboxOverlay.prototype.registerActor@resource://gre/modules/commonjs/toolkit/loader.js -> resource://titlemanager-at-getfirebug-dot-com/lib/main.js:175:18
</pre>

This generates the error :   `registry = ActorRegistryFront(target.client, response);`.
Do you know what's happening ?

**Comment by janodvarko** [comment]
> So I've just tried it out, and I'm a bit deceived that this doesn't work on other runtimes than Firefox. The reason I wanted to use an actor is because I needed to support those targets as well.

What other targets? If you have FirefoxOS in mind, you need to make sure that 'devtools.debugger.forbid-certified-apps' is set to false on that device.

Read more about restricted privileges on Firefox OS:
https://bugzilla.mozilla.org/show_bug.cgi?id=977443#c11

> Anyway, I tried to eliminate the use of listTabs like this : https://pastebin.mozilla.org/8841569 with no success. And now it's failing on every target : 

Looks like the actor isn't properly registered on the backend.

Honza

**Comment by nt1m** [comment]
@janodvarko I had in mind Firefox OS, Chrome Desktop or iOS Safari (the last 2 via Valence).

<blockquote>
Looks like the actor isn't properly registered on the backend.
</blockquote>

So the problem is on the ActorRegistery side ?

**Comment by janodvarko** [comment]
> So the problem is on the ActorRegistery side ?

No. The problem is that `target.form` is a `form` for the current tab and contains only a list of registered tab actors (no global actors), but the registration that happens inside `registerActor` method needs a `response` returned by `listTabs` - this response contains global actors including the actorRegistryActor. So, you need to revert your change.

Honza

**Comment by nt1m** [comment]
@janodvarko I reverted all the changes, but this still doesn't work on Chrome Desktop or Safari iOS targets. I'm still getting this error : https://pastebin.mozilla.org/8841569 , when lanching the web console on these targets (the line numbers are different though since I undid the changes).
Should I file a bug here or on bugzilla ?

**Comment by janodvarko** [comment]
> @janodvarko I reverted all the changes, but this still doesn't work on Chrome Desktop or Safari iOS targets. I'm still getting this error : https://pastebin.mozilla.org/8841569

Looks like wrong pastebin link (I am seeing the changes instead of an error)

>  when lanching the web console on these targets (the line numbers are different though since I undid the changes). Should I file a bug here or on bugzilla ?

Yes, please.
(cross post the bug link here please)

Honza

**Comment by nt1m** [comment]
@janodvarko whoops, meant the error from comment 5.
Also, here's the bug : https://bugzilla.mozilla.org/show_bug.cgi?id=1191750
