### ISSUE TITLE
Rename ToolboxOverlay to MyToolboxOverlay

### ISSUE THREAD

**Issue by groovecoder** [firebug/devtools-extension-examples#5]
This tripped me up for a bit. I thought `ToolboxOverlay` was a class in the DevTools API. Calling it `MyToolboxOverlay` would make the example more clear.

**Comment by janodvarko** [comment]
What specific example do you have in mind?

Honza

**Comment by groovecoder** [comment]
The DomInspector example is the one I'm looking at.

**Comment by janodvarko** [comment]
Renamed for the following examples:
- DomInspector
- NetAnalysis
- TitleManager

Thanks for the report!

Honza
